# Generated by Django 6.0.7 on 2026-07-10 18:25

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('interest', models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothing'), ('FD', 'Food')], max_length=2)),
                ('message', models.TextField()),
            ],
        ),
    ]
