# Generated by Django 6.0.7 on 2026-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='interest',
            field=models.CharField(choices=[('mo', 'mustard oil'), ('gn', 'groundnut oil'), ('so', 'sesame oil'), ('co', 'coconut oil')], max_length=2),
        ),
    ]
